#!/usr/bin/env bash

# Bar configuration
sketchybar --bar height=32 \
                 color=0xdd1e1e2e \
                 position=top \
                 padding_left=20 \
                 padding_right=20 \
                 font_smoothing=true

# Default item properties
sketchybar --default label.color=0xffcdd6f4 \
                      icon.color=0xffcdd6f4 \
                      label.font="CaskaydiaMono Nerd Font:Regular:12.0" \
                      icon.font="CaskaydiaMono Nerd Font:Regular:12.0"

# Add aerospace workspace change event
sketchybar --add event aerospace_workspace_change

# Add aerospace workspaces
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0xff89b4fa \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        label.color=0xff1e1e2e \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Add clock
sketchybar --add item clock right \
    --set clock update_freq=10 \
                 script="sketchybar --set \$NAME label=\"\$(date '+%a %b %d %I:%M %p')\""